# Site settings
title: Nim
description: >
  The Nim programming language is a concise, fast programming language that
  compiles to C, C++ and JavaScript.
baseurl: ""

nim_version: 0.17.2

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true

navigation:
  - title: Blog
    url: /blog.html
  - title: Features
    url: /features.html
  - title: Install
    url: /install.html
  - title: Documentation
    url: /documentation.html
  - title: Forum
    url: https://forum.nim-lang.org
  - title: Donate
    url: /donate.html

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
sass:
  style: compressed
exclude:
  - CNAME
  - README.md
  - LICENSE.md

  